### ISSUE TITLE
Page footer displays in wrong place when preview in Web Viewer/print the report

### ISSUE THREAD

**Issue by nikolaielders** [eclipse/birt#652] opened 2021-05-14 11:08 UTC
Version: [2.5.1]

(![PDF format](https://user-images.githubusercontent.com/84180550/118262491-471b8c00-b4b5-11eb-942a-d6a9751ec9c3.PNG)
![footer view when printing in web viewer](https://user-images.githubusercontent.com/84180550/118262495-47b42280-b4b5-11eb-91de-dd22591ef3fd.PNG)
![footer settings](https://user-images.githubusercontent.com/84180550/118262496-47b42280-b4b5-11eb-9f43-e99d07e2731d.PNG)
![footer](https://user-images.githubusercontent.com/84180550/118262499-47b42280-b4b5-11eb-94f0-f1a885b8543c.PNG)

)

I've set up a complete report and when I want to preview this in web viewer, the page footer is in the middle of the page. Also, if i try to print the report, it will be right after the content instead of in the bottom. It seems to be floating. I can't find how to adjust this setting.
 

Expected result:
Page footer displays at the end of the report.
 
Actual result:
Page footer displayed in the middle of the report right after the last content.
 
Note - When exporting the report to a PDF and print it from there, the page footer is at the bottom. this Only happens in web viewer/html.

I know you asked for the RPT file, unfortunately, the files is within two remote desktops and I currently can't get it to my main computer. Hope the photos works, if not, let me know.

**Comment by hvonbargen** [comment] 2021-05-14 11:46
This is expected behaviour.
If you want to generate a PDF or if you want to print the report, you should not create HTML output with BIRT and then let the browser do the conversion. Instead you should create a PDF *directly*.
The HTML output is meant to be shown in a browser.
Besides, you are using a *very* old BIRT release.

**Comment by wimjongman** [comment] 2021-05-14 13:25
The reason is that HTML does not know the concept of multiple pages. There only is one page. 

If it is really important to you, you might want to look at adding CSS to float the footer to the bottom of the page:

https://forums.opentext.com/forums/developer/discussion/61194/simple-birt-css-style-sheet-example

Closing.

**Closed by wimjongman** 2021-05-14 13:25 UTC

**Comment by nikolaielders** [comment] 2021-05-14 16:05
Hi Both,

Thank you so much for clarifying this for me and the CSS.

Have a great weekend!
