### ISSUE TITLE
Generated Pdf ignores height set (and shown) in report Editor for fixed layout report design

### ISSUE THREAD

**Issue by ivkina** [eclipse/birt#696] opened 2021-11-08 18:11 UTC
Please, see all the details including attachments under https://bugs.eclipse.org/bugs/show_bug.cgi?id=542614

Thanks
Aleksey

>>>>>>>>>>>
Since BIRT v.4.7 (and still in v4.8) the generated Pdf file ignores the height defined in the Report Editor.

This problem affects about 57 report by us.

The root cause is the change from commit f84d0f812a72ba8e54f6caf641e16442d480594c
to the TableLayout class in org.eclipse.birt.report.engine bundle. (I was not able to find any bug ticket related to this commit).

>>>>>>>>>>>>>>>>>

Same issue in 4.9 release candidate. Fixed layout reports rely on row height honored especially when rows are empty as this approach allows to achieve desired layout for pre-printed forms like checks, w-2s, pre-formatted bills or any other reports where fixed/exact presentation is critical.

This is serious, critical issue which makes upgrade from 4.6 to any latest version impossible. 

Seems to be broken in PDF only. All other formats like html, excel, docx and ppt are Ok. But pdf is the most accurate and important format therefore that must  be be supported. Not to mention now you have different output for html vs pdf. 

>>>>>>>>>>>>>>>>>>>>

The problem introduced in https://github.com/eclipse/birt/commit/f84d0f812a72ba8e54f6caf641e16442d480594c

class org.eclipse.birt.report.engine.nLayout.area.impl.TableLayout

line 850-851:
// Do not use specified height if row is empty to avoid endless page break
int sheight = isEmptyRow( rowArea ) ? 0 : rowArea.getSpecifiedHeight( );
int height = sheight;

Should be 
int sheight = rowArea.getSpecifiedHeight( );
int height = sheight;

Then it works fine (as before). Maybe you need to set height to 0 only when layout is NOT fixed, e.g.:
int sheight = (!isFixedLayout && isEmptyRow( rowArea )) ? 0 : rowArea.getSpecifiedHeight( );
int height = sheight;

**Comment by hvbtup** [comment] 2021-11-08 18:51
I think this is a duplicate of https://github.com/eclipse/birt/issues/636. I fixed in similar to this proposal, see https://github.com/eclipse/birt/pull/644

**Comment by ivkina** [comment] 2021-11-08 19:08
if it is fixed, then great...I guess you can close the issue here. we can test the latest build from https://ci.eclipse.org/birt/ and reopen if the issue remains. thanks!

**Comment by hvbtup** [comment] 2021-11-09 06:18
I don't have the privilege to close issues.

**Closed** 2021-11-09 14:22 UTC
