### ISSUE TITLE
QueryResults doesn't close query

### ISSUE THREAD

**Issue by alexanderbecher** [eclipse/birt#966] opened 2022-05-13 10:30 UTC
Hi,

since https://github.com/eclipse/birt/commit/b86b5466030b8e9b684a8fec17081316f19580c0 the query service isn't closed anymore.
If a BIRT report uses many (big) PreparedStatements this leads to massive memory consumption because the JDBC ResultSets are not being closed. 
Because we were experiencing out of memory problems with several big reports in our environment, we've changed QueryResults to close the queryservice and fixed the problem.

I don't know about the "Get page count failed" error that should be fixed with the aformentioned commit so I'm not able to test it in our env.

**Comment by hvbtup** [comment] 2022-05-13 10:33
Duplicate of #875.
This was fixed with #876.

**Closed by hvbtup** 2022-05-13 10:33 UTC
