### ISSUE TITLE
Defective PPTX format in BIRT 4.9.0-20220204-win32

### ISSUE THREAD

**Issue by joachim-wesenberg** [eclipse/birt#813] opened 2022-02-05 11:45 UTC
Using Run/View Report/As PPTX
will generate output which is not recognized by Microsoft Powerpoint nor LibreOffice. It did not work in BIRT 4.7 either. However, in 4.7 the ODP format was supported and could be used to produce PPTX slides via LibreOffice (convert ODP to PPTX) as a workaround.
Are there any plans to have that fixed or would you suggest to stay with BIRT 4.7?

**Comment by claesrosell** [comment] 2022-02-06 10:50
Can you provide an example report that reproduces this error?
I tested with some smaller test-reports that I have and was unable to reproduce this.

**Comment by joachim-wesenberg** [comment] 2022-02-07 14:36
Attached you will find 2 reports:

- test_birt-pptx-output: very small and simple slide - which could be opened in Powerpoint and is ok.
- bav_portfolio_slides: this is the one that gives me grief. It is fine as DOCX, HTML, PDF and ODT. But Powerpoint does not like the format and tries to open with 'Microsoft Open XML Converter'.

Any sort of help is very much appreciated
[birttest.zip](https://github.com/eclipse/birt/files/8016057/birttest.zip)
.

**Comment by claesrosell** [comment] 2022-02-07 16:42
Ok, I have narrowed down this error to a faulty handling of margins in the pptx emitter.
If margins for table contents are set to "Auto", the creation of the pptx will fail because of a NullPointerException.
I will need more time to find out how this special "auto" case should be handled, hopefully I can put more time into this later this week.

**Comment by claesrosell** [comment] 2022-02-08 11:02
@joachim-wesenberg : We have fix for this in PR #818. Please try it out. You can find the builds here: https://github.com/eclipse/birt/actions/runs/1811619251

**Comment by hvbtup** [comment] 2022-02-09 16:24
OP said that PR #818 fixed the issue.

**Closed by hvbtup** 2022-02-09 16:24 UTC
