### ISSUE TITLE
Excel very Slow with large number of groups

### ISSUE THREAD

**Issue by FZOGHLAMI** [eclipse/birt#1216] opened 2023-02-21 10:01 UTC
I have a report with a large number of rows (400k) and a large number of groups (80k).

I want  display data on a single sheet Excel.  (In the table properties ,my Page break is 600k )

**- To generate a report XLSX with 300K rows and  **80K** groups , **it s vers slowly**  ( 14 Hours )**
- To generate a report XLSX  with 300K rows and  20K groups , it s fast (5 Minutes)
   
 If I change page break to 19k , the report run fast with 300k and 80k groups. 
    Any Idea why ?
    Any parametre to modify in Birt engine ?

**Comment by hvbtup** [comment] 2023-02-21 11:09
Huge Excel files are not a good idea generally (not restricted to BIRT).
I can hardly imagine a valid use case.
You should consider other formats and other tools if your goal is to perform something like a database export/import.

**Comment by FZOGHLAMI** [comment] 2023-02-21 13:11
Thank you for the quick reply.
 My goal is not to make database export/import.
 
 It's customer request .
 An Accountant needs to generate an auxiliary scale report  with Excel.
 The report contains between 400K and 1000K rows

**Comment by claesrosell** [comment] 2023-02-21 13:52
Hi
14 hours do seem like a long time.
We would need a simple. reportdesign file with which the performance problem can be reproduced in a developer environment. Can you provide such a test file?

**Comment by FZOGHLAMI** [comment] 2023-02-21 15:06
Hello,
This a single. reportdesign file with which the performance issue can be reproduced in a development environment. 
You need only create many groups data , more than 65K groups.

[BALANCE_AUXILIAIRE_M_COPIE.zip](https://github.com/eclipse/birt/files/10794749/BALANCE_AUXILIAIRE_M_COPIE.zip)

**Comment by hvbtup** [comment] 2023-02-21 16:09
This customer request is still hilarious. Excel is not made for this.
Excel is made for *displaying* and *editing* tabular data of moderate size.
No human will ever look at sheet with 400K rows. At least I'd rather shoot myself.
And for automatic processing of thousands of rows, the Excel format is not well suited, because it contains way too much boilerplate. For such amounts of data, it is way more efficient to create and process CSV files.
Using BIRT for this task is overkill.

**Comment by hvbtup** [comment] 2023-02-21 16:11
... but if you insist on using BIRT, maybe using more groups just means you need more memory?
Did you try using a 64bit Java with a *really* big heap size?
It could be that the JVM is GCing most of the time when available memory is not enough (sorry for my English).

**Comment by hvbtup** [comment] 2023-02-21 17:03
Well, I daresay a Raspi 4 and a few minutes time would easily suffice if you generate a CSV report instead of XLSX with the right tool for the right job (e.g. a little Python script). I did this a few times.

Here I assume that the data source is an SQL database.

The idea is that you let the DB do the heavy lifting and select the data already sorted. Then you don't need to keep the rows in memory, the program can "forget" a row just after it was written to the CSV file.

Such a streaming process is much more difficult when you create XLSX.
I know that the SpudSoft Excel emitter supports special options for this kind of processing (I can't name them, you'd have to look at the source code), but I doubt that this works with grouping.

And reading/processing such a huge XLSX file will also need much more processing power and memory in comparison to reading/processing a CSV file.

Using the XLSX file format for this is just a waste of resources.

No offence meant. I know how clients are...
Maybe hearing that XLSX is not the best interchange format for mass data from a third party can help you convincing them to use a different format.

**Comment by speckyspooky** [comment] 2023-02-21 19:18
Hello together, I can only confirm my writers before the XLSX isn't an data interchange format and also the spudsoft emitter of XLSX won't help you realy. The core is based on the apache POI library.

But the common reason of the long runtime is the internal characteristic of XLSX.
Because the file format is an zip-file which includes different XML-files splitted into different context.
If you use such huge data and groups all data must be handled in memory and the topic is that the XML-document tree must be handled at all.

You can compare it with an large HTML-file which you try to run on your LINUX-128GB-machine with an browser.
The limitation isn't only the physical size. At the end each is fact that operations like search or adding of such structure needs more time direct depending on structure growing.

**Comment by hvbargen** [comment] 2023-02-21 21:12
My fork at https://github.com/triestram-partner/birt contains improvements to the spudsoft emitter, in particular the EXTRACT_MODE option, which uses a POI streaming API.  https://github.com/triestram-partner/birt/blob/tup_main/engine/uk.co.spudsoft.birt.emitters.excel/src/uk/co/spudsoft/birt/emitters/excel/ExcelEmitter.java - this might help in your case. But be warned, the fork contains other differences too. I can't give you an example, you are entering unknown territory here. Maybe the test code contains an example, I don't know...

**Comment by FZOGHLAMI** [comment] 2023-02-22 09:36
Hello ,
The final report XLSX contains **Subtotals** and **Grand totals**. _I can't replace XLSX with CSV format._ 
The final report  XLSX is as follows : 
![BUG_CRE](https://user-images.githubusercontent.com/24314808/220580506-46bb4a1f-3745-4bb9-8670-9110ae603772.png)
![sub-totals](https://user-images.githubusercontent.com/24314808/220580551-0a227332-8a92-4a9d-a460-106d753ea383.png)

**Comment by claesrosell** [comment] 2023-02-22 09:47
I took a look at the code yesterday. 
One of the things that takes a lot of time during the xlsx generation is the creation of Excel row groups. It seems like you can disable the creation of those groups is via a render option called "ExcelEmitter.DisableGrouping".

**Comment by FZOGHLAMI** [comment] 2023-02-22 09:49
Hello,
I run this report format with HTML format. 
**The generation is fast for 900K rows.**

The report HTML file is very large.
I can't display the entire HTML file and can't run search
All browsers are crashing with the out of memory to open this file .
I try with 100K rows , I have the same exception  <<out of memory>>

**Comment by hvbtup** [comment] 2023-02-22 09:52
BTW have you tried if a file with a similar structure and 900K rows is usable in Excel at all on a typical notebook your clients use?

**Comment by FZOGHLAMI** [comment] 2023-02-22 14:12
Yes , a file with a similar structure with 900K and more is usable in Excel on a typical notebook my client.

**Comment by FZOGHLAMI** [comment] 2023-02-22 14:12
I will try the render option DisableGrouping.

**Comment by FZOGHLAMI** [comment] 2023-02-22 15:37
Hello,
I try the render option DisableGrouping  , it's fast for 150K.

I have three groups ,
for 150k rows  , the excel generate 313 082 rows in reality
.

![test_150k](https://user-images.githubusercontent.com/24314808/220666050-7960265e-3349-4ac0-804a-b72410707982.png)

**Comment by FZOGHLAMI** [comment] 2023-02-22 15:40
I run test for 900k rows . But Excel will generate more 1000K  ( ~1500k) in reality.
I have this Exception : java.lang.IllegalArgumentException: Invalid row number (1048576) outside allowable range (0..1048575)

I want ,Excel Page Break Every 1000K Rows( limit XLSK per sheet tab).
Any Idea  ?


![Group_150k](https://user-images.githubusercontent.com/24314808/220674311-25c6e279-1257-486c-bc80-e3d245f6ffbc.png)
![Page_Break](https://user-images.githubusercontent.com/24314808/220674356-405f938d-d5c2-40a0-9ca5-c295ed30b89a.png)

**Comment by FZOGHLAMI** [comment] 2023-02-22 19:55
Hello,
I tried to manually create an exel file with 1400K and  It worked
**We can use many worksheet  with Birt  ?**



![Limite_XLSXpng](https://user-images.githubusercontent.com/24314808/220742332-f354da77-814e-49ac-9938-452ef95486bd.png)

https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3

**Comment by claesrosell** [comment] 2023-02-22 21:00
Try set the ExcelEmitter.SingleSheet render option to false

**Comment by FZOGHLAMI** [comment] 2023-02-23 20:25
Hello,
I Try ExcelEmitter.SingleSheet render option to false.
I have the same exception : 

**Exception : java.lang.IllegalArgumentException: Invalid row number (1048576) outside allowable range (0..1048575)
	at org.apache.poi.xssf.usermodel.XSSFRow.setRowNum(XSSFRow.java:335)
	at org.apache.poi.xssf.usermodel.XSSFSheet.createRow(XSSFSheet.java:539)
	at org.apache.poi.xssf.usermodel.XSSFSheet.createRow(XSSFSheet.java:72)
	at uk.co.spudsoft.birt.emitters.excel.handlers.AbstractRealTableRowHandler.resumeRow(AbstractRealTableRowHandler.java:81)**

**Comment by FZOGHLAMI** [comment] 2023-02-23 20:30
My report returns more than 1,048,576 rows ( Max limit in XLSX)
I want 1,048,576 rows in sheet 0 . and remainning rows in next sheet ( sheet 1 or tab 1)


How I can  configure this With Birt?
if current rows equal 1,048,576 row , I break page ?

**Comment by hvbtup** [comment] 2023-02-27 16:38
Did you try with a page break interval much lower, e.g. 10000?
Keep in mind that it counts the number of details, not the number of excel rows.
There are additional rows for the table/group header/footers.

**Comment by FZOGHLAMI** [comment] 2023-02-28 09:18
Hello,
**I try with a page break interval much lower, e.g. 10000 and It's work well.**

Yes ,There are additional rows for the table/group header/footers.
I don't know the number of groups when I run the report.
The report generate X rows groups .
**Is it possible to control the page break with java script?**


_if(vars["rowcount"] = 50){
reportContext.getDesignHandle().getElementByID(4).setProperty("pageBreakInterval", 8);
}_

**Comment by hvbtup** [comment] 2023-02-28 09:50
I'd rather recommend to control page-breaking (=switch to new sheet for Excel emitter) with the groups themselves, e.g. to set page-break-before: always (or always except first) for one of the groups.
See the page break dialog for the groups.

**Comment by FZOGHLAMI** [comment] 2023-03-03 10:12
Hello, it s good idea but I have three groups .

The client wishes to display the total (group 3) in the same tab.
if I break in group 1, I can't ensure the total in the same page ?


RPTDESIGNT :

![B1](https://user-images.githubusercontent.com/24314808/222693171-2ff517e6-af6f-4f98-b1a1-0796c1edeb9d.png)


VERSION OK

![B2](https://user-images.githubusercontent.com/24314808/222693333-1a712089-9252-4606-88f0-2006be394c00.png)


VERSION NOT OK :

![B3](https://user-images.githubusercontent.com/24314808/222693406-28e5d41e-1e07-4b23-883d-a6b3d1a39a6b.png)

**Comment by hvbtup** [comment] 2023-03-03 11:06
I'm not sure what you want to achieve. For me, the restrictions seem to conflict.

The original issue (slow performance) was solved by setting the render option DisableGrouping.
Then you hit the technical limit of Excel with too many rows in a single sheet, which cannot be solved by BIRT.

Thus limiting the rows on a single sheet is necessary.

The issue you described last is that the "sheet-breaking" does not work like you want it to be.
This is very different from the original issue.

I'll close this issue now to keep it focused on the original problem.

For the "sheet-breaking" issue, I propose that you create a stand-alone report which demonstrates the problem with a much smaller number of rows, a clear description of what the restrictions are and what you want to achieve, and create a separate issue with this information.

**Closed by hvbtup** 2023-03-03 11:06 UTC

**Comment by FZOGHLAMI** [comment] 2023-03-06 11:24
Thanks for your help
