### ISSUE TITLE
BIRT runtime on Tomcat with OpenJDK 15 - java.lang.NoClassDefFoundError: javax.xml.rpc.handler.soap.SOAPMessageContext

### ISSUE THREAD

**Issue by francismarchi** [eclipse/birt#958] opened 2022-05-03 13:06 UTC
## Summary
We encounter an exception while testing a report after deploying the BIRT webapp.

## Steps to reproduce
(How one can reproduce the issue - this is very important)
We first downloading the 'birt-runtime-4.9.0-20220315.zip' file from the 'https://download.eclipse.org/birt/downloads/drops/R-R1-4.9.0-202203161719/' url we deployed the war in a tomcat 9.0.37 with a Java OpenJDK 15.0.1 environment.
After we test a report and we have this exception:
java.lang.NoClassDefFoundError: javax/xml/rpc/handler/soap/SOAPMessageContext

## What is the current bug behavior?
In fact there is a problem in 'javax.xml.rpc_1.1.2.v202203150031.jar' libray file from the war file.
This library embed directly the 'javax.xml.rpc-api-1.1.2.jar' libray file.
When we downaloded 'javax.xml.rpc-api-1.1.2.jar' libray file from the 'https://mvnrepository.com/artifact/javax.xml.rpc/javax.xml.rpc-api/1.1.2' url and replace in the WEB-INF/lib directory all is fine.

## What is the expected correct behavior?
It may therefore be necessary to correct the file 'javax.xml.rpc_1.1.2.v202203150031.jar'.

## Relevant logs and/or screenshots
In logs we have this exception:

javax.servlet.ServletException: Erreur à l'instantiation de la classe servlet [org.eclipse.birt.report.servlet.ViewerServlet]
	org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:373)
	org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1589)
	org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	java.base/java.lang.Thread.run(Thread.java:832)

cause mère
java.lang.NoClassDefFoundError: javax/xml/rpc/handler/soap/SOAPMessageContext
	java.base/java.lang.ClassLoader.defineClass1(Native Method)

**Comment by claesrosell** [comment] 2022-05-03 13:48
First: this is a great bug report!
Secondly, this is probably a duplicate of #941, which have a misleading name (see comment https://github.com/eclipse/birt/issues/941#issuecomment-1100734202).
Please try one of the later 4.10 snapshots (https://github.com/eclipse/birt/actions/runs/2225351625), there are other issues in the Birt runtime fixed in master as well.

**Comment by wimjongman** [comment] 2022-05-03 13:52
Signed snapshots are here:

https://download.eclipse.org/birt/downloads/drops/snapshot/

**Closed** 2022-05-03 14:23 UTC
