### ISSUE TITLE
Some reports created with BIRT 4.2.1 don't work with 4.9.0

### ISSUE THREAD

**Issue by hvbtup** [eclipse/birt#838] opened 2022-02-25 11:02 UTC
Some of our exisiting reports are using the CONCATENATE aggregate function.

When running such a report with BIRT 4.9, the defined properties such as separator, maximum length etc are ignored and the default values are uses (an empty separator and a maximum length of 1000).

This results in incorrect output.

I needed a lot of time to find out what's causing the issue.

In the original report, the properties are defined as follows:

                <structure>
                    <property name="name">all_products</property>
                    <property name="dataType">string</property>
                    <property name="aggregateFunction">CONCATENATE</property>
                    <list-property name="arguments">
                        <structure>
                            <property name="name">Expression</property>
                            <expression name="value">row["PRODUCTNAME"]</expression>
                        </structure>
                        <structure>
                            <property name="name">Separat&amp;or</property>
                            <expression name="value">", "</expression>
                        </structure>
                        <structure>
                            <property name="name">Ma&amp;x length</property>
                            <expression name="value">1000000</expression>
                        </structure>
                        <structure>
                            <property name="name">Sho&amp;w all values</property>
                            <expression name="value">true</expression>
                        </structure>
                    </list-property>
                </structure>

If I open the report in the *new* designer, this is silently converted to

                <structure>
                    <property name="name">all_products</property>
                    <property name="dataType">string</property>
                    <property name="aggregateFunction">CONCATENATE</property>
                    <list-property name="arguments">
                        <structure>
                            <property name="name">Expression</property>
                            <expression name="value">row["PRODUCTNAME"]</expression>
                        </structure>
                        <structure>
                            <property name="name">Separator</property>
                            <expression name="value">", "</expression>
                        </structure>
                        <structure>
                            <property name="name">Maxlength</property>
                            <expression name="value">1000000</expression>
                        </structure>
                        <structure>
                            <property name="name">Showallvalues</property>
                            <expression name="value">true</expression>
                        </structure>

Note that ampersands (to mark the keyboard shortcut key) are present in the old file, but no longer in the new file.

At runtime, the implementation is looking for the "Separator" property but can't find it.

This can only be solved by manually "migrating" the existing rptdesign files to the new format.

Of course, the new format is better, but the necessity of manual migrating existing reports is a PITA.

Question:
Is there a migration guide - or a migration tool?
Does anybody know if there are other such issues?

**Comment by claesrosell** [comment] 2022-02-25 13:43
I will dig in the git commit log and see if I find the reason for this.

**Comment by claesrosell** [comment] 2022-02-25 13:55
I did a small test to reproduce this, but did not succeed. Can you provide a minimal .rptdesign file that reproduces this behavior?

**Comment by hvbtup** [comment] 2022-02-25 14:03
[concatenate_bug.zip](https://github.com/eclipse/birt/files/8141704/concatenate_bug.zip)

The archive contains two reports. The xxx421.rptdesign was created with BIRT 4.2.1 (maybe even with 3.7.1 originally and then opened with 4.2.1). The xxx490.rptdesign is the result of opening it in BIRT 4.9.0.

**Comment by claesrosell** [comment] 2022-02-25 14:20
I can reproduce this by:

- Open up the data set "Data Set"
- Open the "Computed columns" page
- Edit "all_products" in some small way
- Save the design file.

Hopefully I have more time to look into this later this weekend, but I cannot promise anything.

**Comment by claesrosell** [comment] 2022-02-26 14:21
The change in Birt that caused this problem was commited 2014-12-30 , it has been part of Birt since version 4.5.0 and possibly 4.4.2 . Hence, this is a very old and perhaps not very big problem.

One place to do a "silent on-the-fly migration" is in org.eclipse.birt.report.data.adapter.internal.adapter.ComputedColumnAdapter when the arguments are populated, but there may, and hopefully, be better places.

However, the fix will be a ugly hack and may not always work since the old names of these parameters were translated into different languages. Before the fix in 2014, a report design created in France would not work in Spain. The old, problematic, behavior would affect the "silent migration fix" so every translation of these parameters would need to be check and migrated to the new parameter names for such a fix to be robust. 

I will see if I can find a cleaner way to solve this. Perhaps there are some kind of migration step somewhere...

**Comment by hvbtup** [comment] 2022-02-28 08:23
Probably you mean the commit cac6e65a766ecbf1086728cebdbb5d54b4755728, involving Constants.java and TotalConcatenate.java.

In this case it seems that the CONCATENATE aggragate function was the only one affected. That's good to know.

Regarding "Hence, this is a very old and perhaps not very big problem." - There are still many users working with even older BIRT releases than 4.3. Often they say that they can't switch to a newer release for whatever reason. Probably one big reason to not use a newer BIRT release was that BIRT was in effect broken during the last few years - which we will change now :)
So we we might face many questions regarding "what do I have to do to switch from BIRT 3.7, 4.2, 4.3, ... to BIRT 4.9?

The aforementioned commit was a breaking change. I don't know if this has been mentioned anywhere in the old release notes.

I'll close this issue as it is easy to migrate old *.rptdesign files to the new format (as you described in your comment https://github.com/eclipse/birt/issues/838#issuecomment-1050893513) and instead create a new issue for missing documentation.

**Comment by claesrosell** [comment] 2022-02-28 09:41
@hvbtup , I am working on a fix for this that is cleaner, but that still have some limitations. It involves an increase in report design version numbering and performs a migration of the data.
The limitation is that it will only work for reports that was created in designer that used "en" (or root) as Locale. E.g. it uses the property names in your example.

Can you reopen this issue?

**Comment by hvbtup** [comment] 2022-02-28 09:51
A fix would be much better of course. Increasing the version numbering sounds like the right idea.
The limitation is not a limitation in our case, and I guess most of the non-English users use the English designer.
On all my German Windows computers, the BIRT IDE was always showing English texts.

**Closed** 2022-03-05 12:03 UTC
